// <auto-generated />
using System;
using AtmoceSolarApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtmoceSolarApp.Data.Migrations
{
    [DbContext(typeof(AtmocDbContext))]
    [Migration("20260919124451_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AtmoceSolarApp.Models.ApiToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RefreshExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ApiTokens");
                });

            modelBuilder.Entity("AtmoceSolarApp.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Capacity")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastReportedTime")
                        .HasColumnType("datetime2");

                    b.Property<double?>("MaxChargepower")
                        .HasColumnType("float");

                    b.Property<double?>("MaxDischargepower")
                        .HasColumnType("float");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceSerialNumber")
                        .IsUnique();

                    b.HasIndex("SiteId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("AtmoceSolarApp.Models.DeviceAlert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlarmCause")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlarmId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlarmLevel")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AlarmName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AlarmOccurTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AlarmRepairSuggestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AlarmLevel");

                    b.HasIndex("SiteId", "AlarmOccurTime");

                    b.ToTable("DeviceAlerts");
                });

            modelBuilder.Entity("AtmoceSolarApp.Models.DeviceDataSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentPower")
                        .HasColumnType("int");

                    b.Property<double?>("DailyCharging")
                        .HasColumnType("float");

                    b.Property<double?>("DailyDischarge")
                        .HasColumnType("float");

                    b.Property<double>("DailyGeneration")
                        .HasColumnType("float");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int?>("GridVoltage")
                        .HasColumnType("int");

                    b.Property<int?>("GridVoltageA")
                        .HasColumnType("int");

                    b.Property<int?>("GridVoltageB")
                        .HasColumnType("int");

                    b.Property<int?>("GridVoltageC")
                        .HasColumnType("int");

                    b.Property<double>("LifetimeGeneration")
                        .HasColumnType("float");

                    b.Property<double?>("MonthlyCharging")
                        .HasColumnType("float");

                    b.Property<double?>("MonthlyDischarge")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyGeneration")
                        .HasColumnType("float");

                    b.Property<int?>("SOC")
                        .HasColumnType("int");

                    b.Property<DateTime>("SnapshotTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("YearlyGeneration")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "SnapshotTime");

                    b.ToTable("DeviceDataSnapshots");
                });

            modelBuilder.Entity("AtmoceSolarApp.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("BatteryCapacity")
                        .HasColumnType("float");

                    b.Property<string>("BuildState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConstructionMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryGec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryStanag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GridTiedTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MICapacity")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("SolarCapacity")
                        .HasColumnType("float");

                    b.Property<string>("TimeZone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SiteId")
                        .IsUnique();

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("AtmoceSolarApp.Models.SiteDataSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatteryMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BatteryPower")
                        .HasColumnType("int");

                    b.Property<double>("BatterySOC")
                        .HasColumnType("float");

                    b.Property<string>("BatteryStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConsumptionPower")
                        .HasColumnType("int");

                    b.Property<double>("DailyBatteryCharging")
                        .HasColumnType("float");

                    b.Property<double>("DailyBatteryDischarge")
                        .HasColumnType("float");

                    b.Property<double>("DailyConsumption")
                        .HasColumnType("float");

                    b.Property<double>("DailyGridExport")
                        .HasColumnType("float");

                    b.Property<double>("DailyGridImport")
                        .HasColumnType("float");

                    b.Property<double>("DailySolarGeneration")
                        .HasColumnType("float");

                    b.Property<int>("GridPower")
                        .HasColumnType("int");

                    b.Property<double>("LifetimeConsumption")
                        .HasColumnType("float");

                    b.Property<double>("LifetimeGridExport")
                        .HasColumnType("float");

                    b.Property<double>("LifetimeGridImport")
                        .HasColumnType("float");

                    b.Property<double>("LifetimeSolarGeneration")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyConsumption")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyGridExport")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyGridImport")
                        .HasColumnType("float");

                    b.Property<double>("MonthlySolarGeneration")
                        .HasColumnType("float");

                    b.Property<int>("SiteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SnapshotTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("SolarGenerationPower")
                        .HasColumnType("int");

                    b.Property<int>("SolarReactivePower")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalCo2Reduced")
                        .HasColumnType("float");

                    b.Property<double>("TotalTreesPlanted")
                        .HasColumnType("float");

                    b.Property<double>("YearlyBatteryCharging")
                        .HasColumnType("float");

                    b.Property<double>("YearlyBatteryDischarge")
                        .HasColumnType("float");

                    b.Property<double>("YearlyGridExport")
                        .HasColumnType("float");

                    b.Property<double>("YearlyGridImport")
                        .HasColumnType("float");

                    b.Property<double>("YearlySolarGeneration")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("SiteId", "SnapshotTime");

                    b.ToTable("SiteDataSnapshots");
                });

            modelBuilder.Entity("AtmoceSolarApp.Models.Device", b =>
                {
                    b.HasOne("AtmoceSolarApp.Models.Site", "Site")
                        .WithMany("Devices")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("AtmoceSolarApp.Models.DeviceDataSnapshot", b =>
                {
                    b.HasOne("AtmoceSolarApp.Models.Device", "Device")
                        .WithMany("DataSnapshots")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("AtmoceSolarApp.Models.SiteDataSnapshot", b =>
                {
                    b.HasOne("AtmoceSolarApp.Models.Site", "Site")
                        .WithMany("DataSnapshots")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("AtmoceSolarApp.Models.Device", b =>
                {
                    b.Navigation("DataSnapshots");
                });

            modelBuilder.Entity("AtmoceSolarApp.Models.Site", b =>
                {
                    b.Navigation("DataSnapshots");

                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
